steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/snape-demand-aggregation-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/snape-demand-aggregation-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'snape-demand-aggregation-app',
        '--image', 'gcr.io/$PROJECT_ID/snape-demand-aggregation-app',
        '--platform', 'managed',
        '--region', 'us-central1', //need to change this to your region 
        '--allow-unauthenticated',
        '--port', '8501'
      ]

images:
  - gcr.io/$PROJECT_ID/snape-demand-aggregation-app